name: Build Vita Plugin

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: vitasdk/vitasdk:latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Download and Inject taiHEN
        run: |
          # 1. Download official taiHEN headers
          mkdir -p /usr/local/vitasdk/arm-vita-eabi/include
          curl -L https://githubusercontent.com -o /usr/local/vitasdk/arm-vita-eabi/include/taihen.h
          
          # 2. Generate a valid mock stub archive to satisfy the compiler linker flag (-ltaihen)
          arm-vita-eabi-ar rcs /usr/local/vitasdk/arm-vita-eabi/lib/libtaihen.a

      - name: Create Build Environment
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=${VITASDK}/share/vita.toolchain.cmake ..
          make

      - name: Upload Finished Plugin Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fifa14_redirect_suprx
          path: build/*.suprx
